# Generated by Django 3.1 on 2020-08-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mathematics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('quest', models.CharField(max_length=600)),
                ('a', models.CharField(max_length=64)),
                ('b', models.CharField(max_length=64)),
                ('c', models.CharField(max_length=64)),
                ('d', models.CharField(max_length=64)),
                ('correct', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='mathematics2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=3)),
                ('quest', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('score', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
