# Generated by Django 3.1 on 2020-08-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_agric_agric2_bscience_bscience2_bstd_bstd2_btech_btech2_cca_cca2_civic_civic2_crk_crk2_english_engli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='score',
            new_name='scorecrs',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64),
        ),
    ]
