# Generated by Django 3.1 on 2020-08-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200829_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scoreagric',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
